using System.Collections.Generic;

namespace SaveData
{
    /// <summary>
    /// スキルツリーのノード定義一覧
    /// 各項目は単一解放で効果は小さく分割する
    /// </summary>
    public static class SkillTreeCatalog
    {
        private static readonly SkillTreeNodeDefinition[] Nodes =
        {
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Center,
                "基礎体力I",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 25,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHp,
                "基礎体力II",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 35,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f,
                SkillTreeNodeId.Center),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHp2,
                "基礎体力III",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 45,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f,
                SkillTreeNodeId.StartingHp),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHp3,
                "基礎体力IV",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 55,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f,
                SkillTreeNodeId.StartingHp2),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAttack,
                "基礎攻撃I",
                "育成開始時の攻撃が+{0}",
                maxLevel: 1,
                baseCost: 40,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAttack,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHp2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAttack2,
                "基礎攻撃II",
                "育成開始時の攻撃が+{0}",
                maxLevel: 1,
                baseCost: 50,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAttack,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingAttack),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAttack3,
                "基礎攻撃III",
                "育成開始時の攻撃が+{0}",
                maxLevel: 1,
                baseCost: 60,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAttack,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingAttack2),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingDefense,
                "基礎防御I",
                "育成開始時の防御が+{0}",
                maxLevel: 1,
                baseCost: 40,
                costPerLevel: 0,
                SkillTreeEffectType.StartingDefense,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHp2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingDefense2,
                "基礎防御II",
                "育成開始時の防御が+{0}",
                maxLevel: 1,
                baseCost: 50,
                costPerLevel: 0,
                SkillTreeEffectType.StartingDefense,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingDefense),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingDefense3,
                "基礎防御III",
                "育成開始時の防御が+{0}",
                maxLevel: 1,
                baseCost: 60,
                costPerLevel: 0,
                SkillTreeEffectType.StartingDefense,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingDefense2),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingSpeed,
                "基礎速度I",
                "育成開始時の速度が+{0}",
                maxLevel: 1,
                baseCost: 40,
                costPerLevel: 0,
                SkillTreeEffectType.StartingSpeed,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHp2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingSpeed2,
                "基礎速度II",
                "育成開始時の速度が+{0}",
                maxLevel: 1,
                baseCost: 50,
                costPerLevel: 0,
                SkillTreeEffectType.StartingSpeed,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingSpeed),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingSpeed3,
                "基礎速度III",
                "育成開始時の速度が+{0}",
                maxLevel: 1,
                baseCost: 60,
                costPerLevel: 0,
                SkillTreeEffectType.StartingSpeed,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingSpeed2),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHit,
                "基礎命中I",
                "育成開始時の命中が+{0}",
                maxLevel: 1,
                baseCost: 40,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHit,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHp2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHit2,
                "基礎命中II",
                "育成開始時の命中が+{0}",
                maxLevel: 1,
                baseCost: 50,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHit,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHit),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHit3,
                "基礎命中III",
                "育成開始時の命中が+{0}",
                maxLevel: 1,
                baseCost: 60,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHit,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHit2),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAll,
                "総合強化I",
                "育成開始時の全ステが+{0}",
                maxLevel: 1,
                baseCost: 70,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAll,
                effectPerLevel: 4f,
                SkillTreeNodeId.StartingAttack6),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAll2,
                "総合強化II",
                "育成開始時の全ステが+{0}",
                maxLevel: 1,
                baseCost: 90,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAll,
                effectPerLevel: 4f,
                SkillTreeNodeId.StartingDefense6),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAll3,
                "総合強化III",
                "育成開始時の全ステが+{0}",
                maxLevel: 1,
                baseCost: 110,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAll,
                effectPerLevel: 4f,
                SkillTreeNodeId.StartingSpeed6),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess1,
                "集中力I",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 35,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Center),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess2,
                "集中力II",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 45,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess1),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess3,
                "熟練I",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 55,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess4,
                "熟練II",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 70,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess5,
                "達人の境地",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 90,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess4),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney1,
                "お小遣いI",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 25,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.Center),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney2,
                "お小遣いII",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 35,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.StartingMoney1),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney3,
                "貯金上手I",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 45,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.StartingMoney2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney4,
                "貯金上手II",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 60,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.StartingMoney3),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney1,
                "賞金稼ぎI",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 45,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingMoney2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney2,
                "賞金稼ぎII",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 55,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney1),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney3,
                "大口取引I",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 70,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney4,
                "大口取引II",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 85,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney5,
                "商売の極み",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 100,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney4),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain1,
                "戦果の知恵I",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 50,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.Center),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain2,
                "戦果の知恵II",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 65,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain1),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain3,
                "戦果の極みI",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 80,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain4,
                "戦果の極みII",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 100,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain5,
                "戦果の覇者",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 120,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain4),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance1,
                "血脈の力I",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 45,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Center),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance2,
                "血脈の力II",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 60,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance1),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance3,
                "血脈の覚醒I",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 75,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance2),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance4,
                "血脈の覚醒II",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 95,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance5,
                "血脈の極み",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 120,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance4),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHp4,
                "基礎体力V",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 65,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f,
                SkillTreeNodeId.StartingHp3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHp5,
                "基礎体力VI",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 75,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f,
                SkillTreeNodeId.StartingHp4),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHp6,
                "基礎体力VII",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 85,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f,
                SkillTreeNodeId.StartingHp4),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHp7,
                "基礎体力VIII",
                "育成開始時のHPが+{0}",
                maxLevel: 1,
                baseCost: 95,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHp,
                effectPerLevel: 8f,
                SkillTreeNodeId.StartingHp6),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAttack4,
                "基礎攻撃IV",
                "育成開始時の攻撃が+{0}",
                maxLevel: 1,
                baseCost: 70,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAttack,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingAttack3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAttack5,
                "基礎攻撃V",
                "育成開始時の攻撃が+{0}",
                maxLevel: 1,
                baseCost: 80,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAttack,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingAttack3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAttack6,
                "基礎攻撃VI",
                "育成開始時の攻撃が+{0}",
                maxLevel: 1,
                baseCost: 90,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAttack,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingAttack5),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingDefense4,
                "基礎防御IV",
                "育成開始時の防御が+{0}",
                maxLevel: 1,
                baseCost: 70,
                costPerLevel: 0,
                SkillTreeEffectType.StartingDefense,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingDefense3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingDefense5,
                "基礎防御V",
                "育成開始時の防御が+{0}",
                maxLevel: 1,
                baseCost: 80,
                costPerLevel: 0,
                SkillTreeEffectType.StartingDefense,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingDefense3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingDefense6,
                "基礎防御VI",
                "育成開始時の防御が+{0}",
                maxLevel: 1,
                baseCost: 90,
                costPerLevel: 0,
                SkillTreeEffectType.StartingDefense,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingDefense5),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingSpeed4,
                "基礎速度IV",
                "育成開始時の速度が+{0}",
                maxLevel: 1,
                baseCost: 70,
                costPerLevel: 0,
                SkillTreeEffectType.StartingSpeed,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingSpeed3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingSpeed5,
                "基礎速度V",
                "育成開始時の速度が+{0}",
                maxLevel: 1,
                baseCost: 80,
                costPerLevel: 0,
                SkillTreeEffectType.StartingSpeed,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingSpeed3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingSpeed6,
                "基礎速度VI",
                "育成開始時の速度が+{0}",
                maxLevel: 1,
                baseCost: 90,
                costPerLevel: 0,
                SkillTreeEffectType.StartingSpeed,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingSpeed5),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHit4,
                "基礎命中IV",
                "育成開始時の命中が+{0}",
                maxLevel: 1,
                baseCost: 70,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHit,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHit3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHit5,
                "基礎命中V",
                "育成開始時の命中が+{0}",
                maxLevel: 1,
                baseCost: 80,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHit,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHit3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingHit6,
                "基礎命中VI",
                "育成開始時の命中が+{0}",
                maxLevel: 1,
                baseCost: 90,
                costPerLevel: 0,
                SkillTreeEffectType.StartingHit,
                effectPerLevel: 6f,
                SkillTreeNodeId.StartingHit5),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAll4,
                "総合強化IV",
                "育成開始時の全ステが+{0}",
                maxLevel: 1,
                baseCost: 130,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAll,
                effectPerLevel: 4f,
                SkillTreeNodeId.StartingHit6),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingAll5,
                "総合強化V",
                "育成開始時の全ステが+{0}",
                maxLevel: 1,
                baseCost: 150,
                costPerLevel: 0,
                SkillTreeEffectType.StartingAll,
                effectPerLevel: 4f,
                SkillTreeNodeId.StartingHp7),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess6,
                "熟練III",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 110,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess7,
                "達人I",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 130,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess6),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess8,
                "達人II",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 150,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess9,
                "極意I",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 170,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess8),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.GreatSuccess10,
                "極意II",
                "訓練の大成功率が+{0}%",
                maxLevel: 1,
                baseCost: 190,
                costPerLevel: 0,
                SkillTreeEffectType.GreatSuccessPercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.GreatSuccess9),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney5,
                "貯金上手III",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 75,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.StartingMoney4),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney6,
                "財力I",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 90,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.StartingMoney5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney7,
                "財力II",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 105,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.StartingMoney5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.StartingMoney8,
                "財力III",
                "育成開始時の所持金が+{0}G",
                maxLevel: 1,
                baseCost: 120,
                costPerLevel: 0,
                SkillTreeEffectType.StartingMoney,
                effectPerLevel: 50f,
                SkillTreeNodeId.StartingMoney7),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney6,
                "大口取引III",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 115,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney7,
                "商売上手I",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 130,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney6),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney8,
                "商売上手II",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 145,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney3),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney9,
                "商売上手III",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 160,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney8),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.TrainingMoney10,
                "商売の神髄",
                "育成中の獲得金が+{0}%",
                maxLevel: 1,
                baseCost: 180,
                costPerLevel: 0,
                SkillTreeEffectType.TrainingMoneyPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.TrainingMoney9),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain6,
                "戦果の覇者II",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 140,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain7,
                "戦果の覇者III",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 160,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain6),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain8,
                "戦果の伝説I",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 180,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain9,
                "戦果の伝説II",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 200,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain8),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.PointsGain10,
                "戦果の伝説III",
                "対戦で得るポイントが+{0}%",
                maxLevel: 1,
                baseCost: 220,
                costPerLevel: 0,
                SkillTreeEffectType.PointsGainPercent,
                effectPerLevel: 6f,
                SkillTreeNodeId.PointsGain9),

            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance6,
                "血脈の極みII",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 140,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance7,
                "血脈の極みIII",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 160,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance6),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance8,
                "血脈の伝説I",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 180,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance5),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance9,
                "血脈の伝説II",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 200,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance8),
            new SkillTreeNodeDefinition(
                SkillTreeNodeId.Inheritance10,
                "血脈の伝説III",
                "継承のステ上昇率が+{0}%",
                maxLevel: 1,
                baseCost: 220,
                costPerLevel: 0,
                SkillTreeEffectType.InheritancePercent,
                effectPerLevel: 3f,
                SkillTreeNodeId.Inheritance9)
        };

        private static readonly Dictionary<SkillTreeNodeId, SkillTreeNodeDefinition> Map;
        private static readonly SkillTreeEdge[] Edges;

        static SkillTreeCatalog()
        {
            Map = new Dictionary<SkillTreeNodeId, SkillTreeNodeDefinition>(Nodes.Length);
            for (int i = 0; i < Nodes.Length; i++)
            {
                Map[Nodes[i].Id] = Nodes[i];
            }

            var edgeList = new List<SkillTreeEdge>();
            for (int i = 0; i < Nodes.Length; i++)
            {
                SkillTreeNodeDefinition definition = Nodes[i];
                SkillTreeNodeId[] prerequisites = definition.Prerequisites;
                for (int p = 0; p < prerequisites.Length; p++)
                {
                    edgeList.Add(new SkillTreeEdge(prerequisites[p], definition.Id));
                }
            }

            Edges = edgeList.ToArray();
        }

        /// <summary>
        /// 全ノード定義
        /// </summary>
        public static IReadOnlyList<SkillTreeNodeDefinition> AllNodes => Nodes;

        /// <summary>
        /// 前提関係の接続一覧
        /// </summary>
        public static IReadOnlyList<SkillTreeEdge> PrerequisiteEdges => Edges;

        /// <summary>
        /// ノード定義を取得する
        /// </summary>
        /// <param name="id">ノードID</param>
        public static bool TryGet(SkillTreeNodeId id, out SkillTreeNodeDefinition definition)
        {
            return Map.TryGetValue(id, out definition);
        }
    }
}
